# Generated by Django 6.1.1 on 2026-10-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pokedex', models.PositiveIntegerField(unique=True, verbose_name='N° Pokédex')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipo_primario', models.CharField(max_length=50, verbose_name='Tipo Primario')),
                ('tipo_secundario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Secundario')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de la Pokédex')),
                ('activo', models.BooleanField(default=True, verbose_name='Visible en la Wiki')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Pokémon',
                'verbose_name_plural': 'Pokémons',
                'ordering': ['numero_pokedex'],
            },
        ),
    ]
